spring.datasource.url=jdbc:sqlserver://PROD_DB_HOST:1433;databaseName=cart_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=PROD_DB_USERNAME
spring.datasource.password=PROD_DB_PASSWORD
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.kafka.bootstrap-servers=PROD_KAFKA_HOST:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topic.cart-events=cart-events
app.product-service.url=http://product-service:8081